routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('locale/{locale}', 'HomeController@setLocale');

Route::post('/login/active', 'Auth\LoginController@authenticate');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/', 'HomeController@index');

Route::resource('/users', 'UserController');
Route::resource('/jobs', 'JobController');
Route::get('/profile', 'ProfileController@index')->middleware('auth');
Route::post('/profile/photo', 'ProfileController@photo')->middleware('auth');
Route::get('/profile/photo/delete', 'ProfileController@deletePhoto')->middleware('auth');
Route::post('/add/cv','ProfileController@addCv');
Route::get('/remove/cv','ProfileController@removeCv');

Route::get('/jobs/candidature/{id}', 'CandidatureController@addCandidature')->middleware('role:user');
Route::get('/candidatures','CandidatureController@index')->middleware('role:user');

Route::get('/offers','JobController@getOffers')->middleware('role:company');

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

use App\Traits\S3Trait;

class Job extends Model
{

    use S3Trait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_id','user_id','title','description',
        'address','mail','minimal_experience',
        'minimum_knowledge','starting_salary','final_salary',
        'vacancy_number','social_benefit','lat','lon',
        'type_time','type_job','image', 'active', 'featured'
    ];

    public function getCreatedAtAttribute($value) {
        if(isset($value)) {
            $date = new Carbon($value);
            return $date->format('d-m-Y');
        }

        return $value;
    }

    public function getImageAttribute($value) {

        if(config('filesystems.default') == 's3') return $this->getAmazonUrlToken($value);

        if(isset($value)) {
            return asset("storage/$value");
        }

        return $value;
    }

    public function canEdit() {
        $user = auth()->user();
        $user_id = "-1";
        if($user) $user_id = $user->id;
        return $this->user_id == $user_id;
    }

    public function registerToOffert() {
        $user = auth()->user();
        return $this->users()->where('user_id', $user->id)->get()->count();
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}

resources/views/offers/index.blade.php
@extends('templates.front_with_search')

@section('body')
    <div class="container">
        <div class="py-5">

            @include('components.show_messages')

            <div class="d-flex">
                <h3 class="h3 p-b-20px">{{ __('messages.my_offers') }}</h3>
                <a class="ml-auto" href="{{ url('jobs/create') }}">
                    <button class="btn btn-primary btn-sm color-white">{{ __('messages.add') }}</button>
                </a>
            </div>
            @isset($jobs)
            @if(count($jobs))
                <div class=" table-responsive">
                    <table class="profile__table w-100">
                        <tr class="table-title">
                            <th>{{ __('messages.name') }}</th>
                            <th>{{ __('messages.location') }}</th>
                            <th>{{ __('messages.state') }}</th>
                            <th>{{ __('messages.publication_date') }}</th>
                            <th></th>
                        </tr>
                        @foreach($jobs as $job)
                            <tr>
                                <td>{{ $job->title }}</td>
                                <td>{{ $job->address }}</td>
                                <td>
                                    @include('components.job_state', ['job' => $job])
                                </td>
                                <td>{{ $job->created_at }}</td>
                                <td>
                                    <a class="btn-primary btn btn-sm color-white" href="{{ url('jobs') }}/{{ $job->id }}">{{__('messages.see')}}</a>
                                    @if($job->active)
                                        <a class="btn-danger btn btn-sm js-btn-confirm" data-type="job" data-identifier="{{ $job->id }}" href="#">{{__('messages.cancel')}}</a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            @else
                <div>
                    {{ __('messages.offers_no_content') }}
                </div>
            @endif
            <div class="mt-3">
                {{ $jobs->links() }}
            </div>
            @endisset
            {{-- <div class="row">
                <div class="col-12 offset-md-2 col-md-8 ">
                    @foreach($jobs as $job)
                        @component('jobs.job_item',
                                    ['job' => $job,
                                     'more' => 'more'
                                     ])
                        @endcomponent
                    @endforeach
                    {{ $jobs->links() }}
                </div>
            </div> --}}

        </div>

        <!-- Modal -->
        <div class="modal fade bd-example-modal-sm" id="btn-confirm-wrapper" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm" role="document">
                <form class="modal-content" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-header">
                        <h5 class="modal-title">{{ __('messages.my_offers_delete_confirmation') }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-sm " data-dismiss="modal">{{ __('messages.close') }}</button>
                        <button type="submit" class="btn-danger btn btn-sm">{{ __('messages.cancel') }}</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
@endsection